<a href="https://colab.research.google.com/github/BENMEZIAN/NumPy-tutorial/blob/main/Part_01_What_is_NumPy%3F.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Install numpy library
!pip install numpy

In [3]:
# Import NumPy Library
import numpy as np

In [4]:
# Create one dimensional NumPy array
one_d_array = np.array([1,2,3,4]) # create 1D array
print(one_d_array) # printing 1d array

[1 2 3 4]


In [7]:
# Create two dimensional NumPy array
two_d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # create 2D array
print(two_d_array) # printing 2d array

[[1 2 3]
 [4 5 6]
 [7 8 9]]
