<a href="https://colab.research.google.com/github/BENMEZIAN/NumPy-tutorial/blob/main/Part_08_NumPy_array_iterat%2C_search%2C_sort%2C_filter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

# Iterating arrays

In [46]:
# iterating over array
arr = np.array([1, 2, 3])
td_arr = np.array([[1, 2, 3], [4, 5, 6]])

print("1D array elements :")
for x in arr:
  print(x)

print("2D array elements (rows format):")
for x in td_arr:
  print(x)

print("2D array elements (individual elements format):")
for x in td_arr:
  for y in x:
    print(y)

1D array elements :
1
2
3
2D array elements (rows format):
[1 2 3]
[4 5 6]
2D array elements (individual elements format):
1
2
3
4
5
6


# Searching Arrays

In [25]:
# You can search an array for a certain value, and return the indexes that get a match.
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)
y = np.where(arr % 2 == 1)
z = np.where(arr % 2 == 0)

print(x)
print(y)
print(z)

sorted_arr = np.array([1,2,3,4,5,6,7,8,9,10])

s = np.searchsorted(sorted_arr, 7)
s2 = np.searchsorted(sorted_arr, 7, side='right')

print(s)
print(s2) # the position right after the last occurrence of 7


# print(arr[x]) # Output : [4 4 4]
# print(arr[y]) # Output : [1 3 5]
# print(arr[z]) # Output : [2 4 4 4]
# print(sorted_arr[s]) # Output : 7
# print(sorted_arr[s2]) # Output : 8

(array([3, 5, 6]),)
(array([0, 2, 4]),)
(array([1, 3, 5, 6]),)
6
7


# Sorting Arrays

In [26]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [27]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr)) # With alphabetical order

['apple' 'banana' 'cherry']


In [29]:
arr = np.array([True, False, True, False])

print(np.sort(arr))

[False False  True  True]


In [32]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


# Filtering Arrays

In [33]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [35]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [36]:
# Create a filter array that will return only even elements from the original array
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [41]:
# Create an array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

filtered_array = array[array > 5] # Filter elements greater than 5
even_numbers = array[array % 2 == 0] # Filter even numbers
odd_numbers = array[array % 2 != 0] # Filter odd numbers
filtered_array2 = array[np.logical_and(array > 5, array % 2 == 0)] # Filter even numbers greater than 5
filtered_array3 = array[np.logical_or(array > 5, array % 2 == 0)] # Filter elements greater than 5 or even numbers
filtered_array4 = array[np.logical_not(array > 5)] # Filter elements not greater than 5
filtered_array5 = array[(array > 5) & (array % 2 == 0)] # Filter even numbers greater than 5
filtered_array6 = array[(array > 5) | (array % 2 == 0)] # Filter elements greater than 5 or even numbers
filtered_array7 = array[~(array > 5)] # Filter elements not greater than 5
filtered_array8 = array[np.isin(array, [1, 3, 5])] # Filter elements that are in [1, 3, 5]

print("Greater than 5 : ",filtered_array)  # Output: [6 7 8 9]
print("Even numbers : ",even_numbers)  # Output: [2 4 6 8]
print("Odd numbers : ",odd_numbers)  # Output: [1 3 5 7 9]
print("Even numbers greater than 5 : ",filtered_array2)  # Output: [6 8]
print("Elements greater than 5 or even numbers : ",filtered_array3)  # Output: [2 4 6 7 8 9]
print("Elements not greater than 5 : ",filtered_array4)  # Output: [1 2 3 4 5]
print("Even numbers greater than 5 : ",filtered_array5)  # Output: [6 8]
print("Elements greater than 5 or even numbers : ",filtered_array6)  # Output: [2 4 6 7 8 9]
print("Elements not greater than 5 : ",filtered_array7)  # Output: [1 2 3 4 5]
print("Elements that are in [1, 3, 5] : ",filtered_array8)  # Output: [1 3 5]

Greater than 5 :  [6 7 8 9]
Even numbers :  [2 4 6 8]
Odd numbers :  [1 3 5 7 9]
Even numbers greater than 5 :  [6 8]
Elements greater than 5 or even numbers :  [2 4 6 7 8 9]
Elements not greater than 5 :  [1 2 3 4 5]
Even numbers greater than 5 :  [6 8]
Elements greater than 5 or even numbers :  [2 4 6 7 8 9]
Elements not greater than 5 :  [1 2 3 4 5]
Elements that are in [1, 3, 5] :  [1 3 5]
