<a href="https://colab.research.google.com/github/BENMEZIAN/NumPy-tutorial/blob/main/Part_03_arrays_in_NumPy_(second_part).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
# Create one dimensional NumPy array, use np.ones()
ones_array = np.ones(4) # create 1D array
print(ones_array) # printing 1d array
print("------------------------------")
print("Information of this array :")
print("type(one_d_array) is :",type(ones_array)) # printing type of array
print("Dtype of one_d_array is :",ones_array.dtype) # printing dtype of array
print("Dimension of one_d_array is :",ones_array.ndim, "dimension(s)") # printing dimension of array
print("Size of one_d_array is :",ones_array.size, "elements") # printing size of array
print("Shape of one_d_array is :",ones_array.shape) # printing shape of array  (columns, )
print("------------------------------")



[1. 1. 1. 1.]
------------------------------
Information of this array :
type(one_d_array) is : <class 'numpy.ndarray'>
Dtype of one_d_array is : float64
Dimension of one_d_array is : 1 dimension(s)
Size of one_d_array is : 4 elements
Shape of one_d_array is : (4,)
------------------------------


In [9]:
# Create two diemensional NumPy array, use ones()
arr = np.ones((3, 4), dtype=float)  # 3x4 2D array of ones with dtype = int (it could : int, float)
print(arr)
print("------------------------------")
print("Information of this array :")
print("type(one_d_array) is :",type(arr)) # printing type of array
print("Dtype of one_d_array is :",arr.dtype) # printing dtype of array
print("Dimension of one_d_array is :",arr.ndim, "dimension(s)") # printing dimension of array
print("Size of one_d_array is :",arr.size, "elements") # printing size of array
print("Shape of one_d_array is :",arr.shape) # printing shape of array (rows,columns)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
------------------------------
Information of this array :
type(one_d_array) is : <class 'numpy.ndarray'>
Dtype of one_d_array is : float64
Dimension of one_d_array is : 2 dimension(s)
Size of one_d_array is : 12 elements
Shape of one_d_array is : (3, 4)


In [11]:
# Crete one dimensional array using zeros()
zeros_array = np.zeros(4, dtype=int) # create 1D array
print(zeros_array) # printing 1d array
print("------------------------------")
print("Information of this array :")
print("type(one_d_array) is :",type(zeros_array)) # printing type of array
print("Dtype of one_d_array is :",zeros_array.dtype) # printing dtype of array
print("Dimension of one_d_array is :",zeros_array.ndim, "dimension(s)") # printing dimension of array
print("Size of one_d_array is :",zeros_array.size, "elements") # printing size of array
print("Shape of one_d_array is :",zeros_array.shape) # printing shape of array  (columns, )

[0 0 0 0]
------------------------------
Information of this array :
type(one_d_array) is : <class 'numpy.ndarray'>
Dtype of one_d_array is : int64
Dimension of one_d_array is : 1 dimension(s)
Size of one_d_array is : 4 elements
Shape of one_d_array is : (4,)


In [13]:
# Create two dimensional array using zeros()
zeros_array = np.zeros((3, 4), dtype=float) # create 2D array
print(zeros_array) # printing 2d array
print("------------------------------")
print("Information of this array :")
print("type(one_d_array) is :",type(zeros_array)) # printing type of array
print("Dtype of one_d_array is :",zeros_array.dtype) # printing dtype of array
print("Dimension of one_d_array is :",zeros_array.ndim, "dimension(s)") # printing dimension of array
print("Size of one_d_array is :",zeros_array.size, "elements") # printing size of array
print("Shape of one_d_array is :",zeros_array.shape) # printing shape of array  (rows, columns)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
------------------------------
Information of this array :
type(one_d_array) is : <class 'numpy.ndarray'>
Dtype of one_d_array is : float64
Dimension of one_d_array is : 2 dimension(s)
Size of one_d_array is : 12 elements
Shape of one_d_array is : (3, 4)


In [22]:
# Use empty()
empty_array = np.empty((3, 4), dtype=bool, order='C') # create 2D array
print(empty_array) # printing 2d array

[[False False False False]
 [False False False False]
 [False False False False]]
