<a href="https://colab.research.google.com/github/BENMEZIAN/NumPy-tutorial/blob/main/Part_06_Python_NumPy_Array_Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# Create one dimensioanl array
one_dim_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(one_dim_array)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
# How to access an element
print(one_dim_array[0])
print(one_dim_array[1])
print(one_dim_array[2])
print(one_dim_array[3])

1
2
3
4


In [5]:
# Create array with arange function
arr_arange = np.arange(1, 101).reshape(10, 10)
print(arr_arange)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [9]:
print(arr_arange[0]) # first row
print(arr_arange[1]) # second row
print(arr_arange[2]) # third row
print(arr_arange[3]) # fourth row

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]
[21 22 23 24 25 26 27 28 29 30]
[31 32 33 34 35 36 37 38 39 40]


In [10]:
print(arr_arange[0][0]) # first element of first row
print(arr_arange[0][1]) # second element of first row
print(arr_arange[0][2]) # third element of first row

1
2
3


In [14]:
arr_arange[:, 0] # all the rows, the first column
arr_arange[:, 0:1] # all the rows, first colum

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [16]:
arr_arange[1:4, 1:4] # rows from 1 to 3, columns from 1 to 3, we exclude the 4th row and column

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])

In [17]:
arr_arange[:, 1:3]

array([[ 2,  3],
       [12, 13],
       [22, 23],
       [32, 33],
       [42, 43],
       [52, 53],
       [62, 63],
       [72, 73],
       [82, 83],
       [92, 93]])

In [18]:
arr_arange[:] # same as arr_arange[:, :]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [19]:
arr_arange.itemsize # the length of the sliced part

8

In [21]:
arr_arange.dtype # the data type of the sliced part

dtype('int64')