<a href="https://colab.research.google.com/github/BENMEZIAN/NumPy-tutorial/blob/main/Part_04_arrays_in_NumPy_(third_part).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
# Create one dimensional NumPy array, use np.arange()
one_d_array = np.arange(10) # create 1D array
print("One dimensional NumPy array :",one_d_array)
print("------------------------------")
print("Information of this array :")
print("type(one_d_array) is :",type(one_d_array)) # printing type of array
print("Dtype of one_d_array is :",one_d_array.dtype) # printing dtype of array
print("Dimension of one_d_array is :",one_d_array.ndim, "dimension(s)") # printing dimension of array
print("Size of one_d_array is :",one_d_array.size, "elements") # printing size of array
print("Shape of one_d_array is :",one_d_array.shape) # printing shape of array  (columns, )

One dimensional NumPy array : [0 1 2 3 4 5 6 7 8 9]
------------------------------
Information of this array :
type(one_d_array) is : <class 'numpy.ndarray'>
Dtype of one_d_array is : int64
Dimension of one_d_array is : 1 dimension(s)
Size of one_d_array is : 10 elements
Shape of one_d_array is : (10,)


In [5]:
# Create array with linespace()
linspace_array = np.linspace(0, 10, 5) # create array with linespace()
print("Array with linespace() :",linspace_array)
print("------------------------------")
print("Information of this array :")
print("type(linspace_array) is :",type(linspace_array)) # printing type of array
print("Dtype of linspace_array is :",linspace_array.dtype) # printing dtype of array
print("Dimension of linspace_array is :",linspace_array.ndim, "dimension(s)") # printing dimension of array
print("Size of linspace_array is :",linspace_array.size, "elements") # printing size of array
print("Shape of linspace_array is :",linspace_array.shape) # printing shape of array  (columns, )

Array with linespace() : [ 0.   2.5  5.   7.5 10. ]
------------------------------
Information of this array :
type(linspace_array) is : <class 'numpy.ndarray'>
Dtype of linspace_array is : float64
Dimension of linspace_array is : 1 dimension(s)
Size of linspace_array is : 5 elements
Shape of linspace_array is : (5,)


In [7]:
# Reshape one_array
reshaped_one_d_array = one_d_array.reshape(2, 5) # reshape 1D array to 2D array
print(reshaped_one_d_array)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [11]:
# Reshape with three parameters, ensuring the product of dimensions matches the original array size
reshaped_one_d_array_3 = one_d_array[:8].reshape(2, 2, 2)  # reshape a slice of the 1D array to 3D array
print(reshaped_one_d_array_3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [15]:
one_d_array = reshaped_one_d_array.ravel() # from 2D into 1D array
print(one_d_array)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
one_d_array = reshaped_one_d_array_3.ravel() # from 3D into 2D array
print(one_d_array)

[0 1 2 3 4 5 6 7]


In [18]:
# flatten
flattened_one_d_array = reshaped_one_d_array.flatten() # flatten 2D array to 1D array
print(flattened_one_d_array)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
# Create 2D array one do its transpose
two_d_array = np.array([[1, 2, 3], [4, 5, 6]]) # create 2D array
print(two_d_array)
print("------------------------------")
print("Information of this array :")
print("type(two_d_array) is :",type(two_d_array)) # printing type of array
print("Dtype of two_d_array is :",two_d_array.dtype) # printing dtype of array
print("Dimension of two_d_array is :",two_d_array.ndim, "dimension(s)") # printing dimension of array
print("Size of two_d_array is :",two_d_array.size, "elements") # printing size of array
print("Shape of two_d_array is :",two_d_array.shape) # printing shape of array  (rows, columns)
print("Transpose of two_d_array is :",two_d_array.T) # printing transpose of array

[[1 2 3]
 [4 5 6]]
------------------------------
Information of this array :
type(two_d_array) is : <class 'numpy.ndarray'>
Dtype of two_d_array is : int64
Dimension of two_d_array is : 2 dimension(s)
Size of two_d_array is : 6 elements
Shape of two_d_array is : (2, 3)
Transpose of two_d_array is : [[1 4]
 [2 5]
 [3 6]]
