<a href="https://colab.research.google.com/github/BENMEZIAN/NumPy-tutorial/blob/main/Part_10_Random_sampling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np

In [16]:
# prompt: Little resume about random sampling in numpy

# Random sampling in NumPy

# 1. `np.random.rand(d0, d1, ..., dn)`: Generate random floats in the half-open interval [0.0, 1.0).
#    - `d0, d1, ..., dn`: Dimensions of the returned array.

# Example: Generate a 3x2 array of random floats
random_floats = np.random.rand(3, 2)
print("Random floats:\n", random_floats)

# Example: Generate 5 random integers between 0 and 10 (exclusive)
random_integers = np.random.randint(0, 10, size=5)
print("\nRandom integers:\n", random_integers)

# Example: Choose 3 elements from [1, 2, 3, 4, 5] with replacement, with equal probability
random_choices = np.random.choice([1, 2, 3, 4, 5], size=3, replace=True)
print("\nRandom choices:\n", random_choices)

# Example: Shuffle a list
my_list = [1, 2, 3, 4, 5]
np.random.shuffle(my_list)
print("\nShuffled list:\n", my_list)

# Example: Permute the numbers 0 to 4
permuted_array = np.random.permutation(5)
print("\nPermuted array:\n", permuted_array)


Random floats:
 [[0.03563322 0.5088469 ]
 [0.69171539 0.42154936]
 [0.21875512 0.89275222]]

Random integers:
 [2 0 5 7 5]

Random choices:
 [1 5 1]

Shuffled list:
 [1, 2, 3, 5, 4]

Permuted array:
 [0 4 2 1 3]


In [ ]:
comment = """Summary of Key Functions:
np.random.rand(): Generates random values between 0 and 1.
np.random.random(): Similar to rand() but allows you to specify shape.
np.random.randn(): Generates random values from a standard normal distribution.
np.random.normal(): Generates random values from a normal distribution with specified mean and standard deviation.
np.random.choice(): Samples random values from a given 1D array.
np.random.randint(): Generates random integers from a specified range.
np.random.permutation(): Randomly permutes an array.
np.random.shuffle(): Shuffles the elements of an array in place."""