<a href="https://colab.research.google.com/github/BENMEZIAN/NumPy-tutorial/blob/main/Part_05_Mathematical_operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [21]:
# Create two two dimensional arrays in order to apply the mathematical operations
first_array = np.array([[1, 2, 3], [4, 5, 6]])
second_array = np.array([[7, 8, 9], [10, 11, 12]])
# arr to do matix product
third_array = np.array([[1, 2], [3, 4], [5, 6]])

print(first_array + second_array)
print("--------------------------")
print(first_array - second_array)
print("--------------------------")
print(first_array * second_array) # or np.multiply(first_array, second_array)
print("--------------------------")
print(first_array / second_array)
print("--------------------------")
print(first_array % second_array)
print("--------------------------")
print(first_array @ third_array) # or np.matmul(first_array, third_array)
print("--------------------------")
print(first_array ** second_array)

[[ 8 10 12]
 [14 16 18]]
--------------------------
[[-6 -6 -6]
 [-6 -6 -6]]
--------------------------
[[ 7 16 27]
 [40 55 72]]
--------------------------
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]
--------------------------
[[1 2 3]
 [4 5 6]]
--------------------------
[[22 28]
 [49 64]]
--------------------------
[[         1        256      19683]
 [   1048576   48828125 2176782336]]


In [33]:
# Built-in functions
print(first_array.max())
print(first_array.argmax())
print("-------------------")
print(first_array.min())
print(first_array.argmin())
print("-------------------")
print(first_array.sum())
print("-------------------")
print(first_array.mean())
print("-------------------")
print(first_array.std())
print("-------------------")
print(np.sqrt(first_array))
print("-------------------")
print(np.log(first_array))
print("-------------------")
print(np.log10(first_array))
print("-------------------")
print(np.exp(first_array))
print("-------------------")
print(np.sin(first_array))
print("-------------------")
print(np.cos(first_array))
print("-------------------")
print(np.tan(first_array))
print("-------------------")

6
5
-------------------
1
0
-------------------
21
-------------------
3.5
-------------------
1.707825127659933
-------------------
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
-------------------
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]
-------------------
[[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125]]
-------------------
[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
-------------------
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
-------------------
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]
-------------------
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]]
-------------------


In [ ]:
# Conclusion
# In the blog of NumPy mathematical functions, we covered the most useful mathematical functions.
# These are the best to solve machine learning and data science project.