<a href="https://colab.research.google.com/github/BENMEZIAN/NumPy-tutorial/blob/main/Part_02_arrays_in_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [26]:
# Create one dimensional NumPy array
one_d_array = np.array([1,2,3,4]) # create 1D array
print(one_d_array) # printing 1d array
print("------------------------------")
print("Information of this array :")
print("type(one_d_array) is :",type(one_d_array)) # printing type of array
print("Dtype of one_d_array is :",one_d_array.dtype) # printing dtype of array
print("Dimension of one_d_array is :",one_d_array.ndim, "dimension(s)") # printing dimension of array
print("Size of one_d_array is :",one_d_array.size, "elements") # printing size of array
print("Shape of one_d_array is :",one_d_array.shape) # printing shape of array  (columns, )

[1 2 3 4]
------------------------------
Information of this array :
type(one_d_array) is : <class 'numpy.ndarray'>
Dtype of one_d_array is : int64
Dimension of one_d_array is : 1 dimension(s)
Size of one_d_array is : 4 elements
Shape of one_d_array is : (4,)


In [25]:
# Create two diemensional NumPy array
two_d_array = np.array([[1,2,3],[4,5,6],[7,8,9]]) # create 2D array
print(two_d_array) # printing 2d array
print("------------------------------")
print("Information of this array :")
print("type(one_d_array) is :",type(two_d_array)) # printing type of array
print("Dtype of one_d_array is :",two_d_array.dtype) # printing dtype of array
print("Dimension of one_d_array is :",two_d_array.ndim, "dimension(s)") # printing dimension of array
print("Size of one_d_array is :",two_d_array.size, "elements") # printing size of array
print("Shape of one_d_array is :",two_d_array.shape) # printing shape of array (rows,columns)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------------------------
Information of this array :
type(one_d_array) is : <class 'numpy.ndarray'>
Dtype of one_d_array is : int64
Dimension of one_d_array is : 2 dimension(s)
Size of one_d_array is : 9 elements
Shape of one_d_array is : (3, 3)
