<a href="https://colab.research.google.com/github/BENMEZIAN/NumPy-tutorial/blob/main/Part_07_Python_NumPy_array_concatenation_and_split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Concatenating Arrays with Same Dimensions

In [37]:
# concatenate two one dimensional arrays
first_array = np.array([1, 2, 3])
second_array = np.array([4, 5, 6])
concatenated_array = np.concatenate((first_array, second_array))
print(concatenated_array)

concatenated_array = np.concatenate((first_array, second_array), axis = None)
print(concatenated_array)

concatenated_array = np.concatenate((first_array, second_array), axis = 0) # axis = 0 means ROWS
print(concatenated_array)

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [39]:
# concatenate two dimensional arrays
first_array = np.array([[1, 2, 3],
                        [4, 5, 6]])
second_array = np.array([[7, 8, 9],
                        [10, 11, 12]])

concatenated_array = np.concatenate((first_array, second_array))
print(concatenated_array)

concatenated_array = np.concatenate((first_array, second_array), axis = None)
print(concatenated_array)

print("Concatenate with rows : ")
concatenated_array = np.concatenate((first_array, second_array), axis = 0) # ROWS
print(concatenated_array)

print("Concatenate with columns : ")
concatenated_array = np.concatenate((first_array, second_array), axis = 1) # COLUMNS
print(concatenated_array)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Concatenate with rows : 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Concatenate with columns : 
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


# Concatenating Arrays with Different Dimensions

In [42]:
# concat two arrays with different dimensions
first_array = np.array([1, 2, 3])
second_array = np.array([[4, 5, 6],
                        [7, 8, 9]])

# use vstack for vertically (rows, axis = 0)
concatenated_array = np.vstack((first_array, second_array))
print(concatenated_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
# create two different arrays
first_array = np.array([[1, 2, 3],
                        [4, 5, 6]])
second_array = np.array([[7, 8],
                        [9, 10]])

# use hstack for horizontally (columns axis 1)
concatenated_array = np.hstack((first_array, second_array))
print(concatenated_array)

[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


# Split array

In [56]:
# Split array
# example
array = np.array([1, 2, 3, 4, 5, 6])
np.array_split(array, 4)

[array([1, 2]), array([3, 4]), array([5]), array([6])]

In [57]:
# another example
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
np.array_split(array, 3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [58]:
# Use hsplit and vsplit

array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
np.hsplit(array, 3)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [59]:
# vsplit

array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
np.vsplit(array, 3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]